/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FiguresIndexRouteImport } from './routes/figures/index'
import { Route as FiguresIdRouteImport } from './routes/figures/$id'

const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresIndexRoute = FiguresIndexRouteImport.update({
  id: '/figures/',
  path: '/figures/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresIdRoute = FiguresIdRouteImport.update({
  id: '/figures/$id',
  path: '/figures/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/places': typeof PlacesRoute
  '/figures/$id': typeof FiguresIdRoute
  '/figures': typeof FiguresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/places': typeof PlacesRoute
  '/figures/$id': typeof FiguresIdRoute
  '/figures': typeof FiguresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/places': typeof PlacesRoute
  '/figures/$id': typeof FiguresIdRoute
  '/figures/': typeof FiguresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events' | '/places' | '/figures/$id' | '/figures'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events' | '/places' | '/figures/$id' | '/figures'
  id: '__root__' | '/' | '/events' | '/places' | '/figures/$id' | '/figures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  PlacesRoute: typeof PlacesRoute
  FiguresIdRoute: typeof FiguresIdRoute
  FiguresIndexRoute: typeof FiguresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/': {
      id: '/figures/'
      path: '/figures'
      fullPath: '/figures'
      preLoaderRoute: typeof FiguresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/$id': {
      id: '/figures/$id'
      path: '/figures/$id'
      fullPath: '/figures/$id'
      preLoaderRoute: typeof FiguresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  PlacesRoute: PlacesRoute,
  FiguresIdRoute: FiguresIdRoute,
  FiguresIndexRoute: FiguresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
